application: erpreciso-blog-challenge
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: erpreciso-blog-challenge.app

libraries:
- name: jinja2
  version: latest
